apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forest-bot-ingress
  namespace: forest-development
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-production-http
  labels:
    name: forest-bot-ingress
    app: forest-bot
spec:
  rules:
  - host: forest-bot.forest.mobilecoin.com
    http:
      paths:
      - pathType: Prefix
        path: "/inbound"
        backend:
          service:
            name: forest-bot-service
            port: 
              number: 8080

  tls:
    - hosts:
      - forest-bot.forest.mobilecoin.com
      secretName: forest-bot.forest.mobilecoin.com-tls
