apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forest-bot-data-pvc
  namespace: forest-development
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
